services:
  db:
    image: postgres:16-alpine
    container_name: icharm-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${ICHARM_DB_USER:-icharm_user}
      POSTGRES_PASSWORD: ${ICHARM_DB_PASSWORD:-icharm_dev_password}
      POSTGRES_DB: ${ICHARM_DB_NAME:-icharm_chat}
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=en_US.UTF-8
    ports:
      - "${ICHARM_DB_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U "${ICHARM_DB_USER:-icharm_user}" -d "${ICHARM_DB_NAME:-icharm_chat}"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  llm-service:
    build:
      context: .
      dockerfile: services/llm-service/Dockerfile
    container_name: icharm-llm-service
    restart: unless-stopped
    environment:
      HF_TOKEN: ${HF_TOKEN:-}
      LLAMA_API_KEY: ${LLAMA_API_KEY:-}
      LLAMA_MODEL: ${LLAMA_MODEL:-meta-llama/Llama-3.1-8B-Instruct}
      HF_CHAT_URL: ${HF_CHAT_URL:-https://router.huggingface.co/v1/chat/completions}
    ports:
      - "${LLM_SERVICE_PORT:-8001}:8000"
    depends_on:
      db:
        condition: service_started

  data-api:
    build:
      context: .
      dockerfile: services/data-api/Dockerfile
    container_name: icharm-data-api
    restart: unless-stopped
    volumes:
      - ./metadata.csv:/app/metadata.csv:ro
      - ./metadata.csv:/app/data/metadata.csv:ro
      - ./datasets:/app/datasets:ro
    ports:
      - "${DATA_API_PORT:-8002}:8000"

volumes:
  postgres-data:
    driver: local
